name: setup-backend
description: Sets up runner environment for backend code.


inputs:
  python-version:
    description: Python version to use
    default: '3.8'
    required: false
    type: string
  pipenv-version:
    description: Pipenv version to use
    default: '2022.1.8'
    required: false
    type: string


runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}

    - uses: actions/cache@v2
      id: cache-pipenv
      with:
        path: |
          ${{ env.pythonLocation }}/bin/pipenv
          ${{ env.pythonLocation }}/lib/python${{ inputs.python-version }}/site-packages/pipenv
        key: ${{ runner.os }}-python${{ inputs.python-version }}-pipenv${{ inputs.pipenv-version }}
        restore-keys: ${{ runner.os }}-python${{ inputs.python-version }}-pipenv

    - name: conditionally install pipenv
      shell: bash
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      working-directory: ./backend
      run: pip install pipenv==${{ inputs.pipenv-version }}

    - uses: actions/cache@v2
      id: cache-lockfile
      with:
        path: ./backend/.venv
        key: ${{ runner.os }}-python${{ inputs.python-version }}-lockfile${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: ${{ runner.os }}-python${{ inputs.python-version }}-lockfile

    - name: conditionally install dependencies
      shell: bash
      if: steps.cache-lockfile.outputs.cache-hit != 'true'
      working-directory: ./backend
      run: pipenv install --dev --deploy
      env:
        PIPENV_VENV_IN_PROJECT: 1
