name: lint-backend
description: lint the backend code using common defaults.

runs:
  using: composite
  steps:
    - uses: isort/isort-action@v1
      with:
        sort-paths: backend
        configuration: --check-only --diff --profile black --verbose

    - uses: psf/black@22.12.0
      with:
        src: backend
