name: lint-backend
description: lint the backend code using common defaults.

runs:
  using: composite
  steps:
    - uses: isort/isort-action@v1
       with:
         isort-version: "5.12.0"
         sort-paths: backend
         configuration: --check-only --diff --profile black --verbose

    - uses: psf/black@22.12.0
      with:
        version: "22.12.0"
        src: backend
