name: setup-frontend
description: Sets up runner environment for frontend code.


inputs:
  node-version:
    description: Node.js version to use
    default: '12'
    required: false
    type: string
  yarn-version:
    description: Yarn version to use
    default: '1.22.15'
    required: false
    type: string


runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: set helper variable
      shell: bash
      run: echo "${name}=$(${value})" >> $GITHUB_ENV
      env:
        name: my_yarn_cache_path
        value: yarn cache dir

    - uses: actions/cache@v2
      id: cache-yarn
      with:
        path: |
          /usr/local/bin/yarn*
          /usr/local/lib/node_modules/yarn
        key: ${{ runner.os }}-node${{ inputs.node-version }}-yarn${{ inputs.yarn-version }}
        restore-keys: ${{ runner.os }}-node${{ inputs.node-version }}-yarn

    - name: conditionally install yarn
      shell: bash
      if: steps.cache-yarn.outputs.cache-hit != 'true'
      working-directory: ./frontend
      run: npm install --global yarn@${{ inputs.yarn-version }}

    - uses: actions/cache@v2
      id: cache-lockfile
      with:
        path: |
          **/node_modules
          ${{ env.my_yarn_cache_path }}
        key: ${{ runner.os }}-node${{ inputs.node-version }}-lockfile${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-node${{ inputs.node-version }}-lockfile

    - name: conditionally install dependencies
      shell: bash
      if: steps.cache-lockfile.outputs.cache-hit != 'true'
      working-directory: ./frontend
      run: >
        yarn install
        --frozen-lockfile
        --non-interactive
        --prefer-offline
        --ignore-scripts
