name: pack-backend
description: Packs backend for deployment and uploads artifact.

inputs:
  environment-name:
    description: environment name
    required: true
    type: string
  environment-url:
    description: environment url
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: pack dependencies
      shell: bash
      working-directory: backend
      run: make pack-backend

    - uses: actions/upload-artifact@v3
      with:
        name: backend
        path: ./lambda.zip
        retention-days: 1
        if-no-files-found: error
