name: test if yaml files are valid

on:
  pull_request:
    paths: ['**/**.yml', '**/**.yaml']
  push:
    paths: ['**/**.yml', '**/**.yaml']

jobs:
  test-yaml:
    uses: ./.github/workflows/call-validate-data-files.yml
