name: validate

on:
  pull_request:
    paths: ['**/**.yml', '**/**.yaml']
  push:
    paths: ['**/**.yml', '**/**.yaml']

jobs:
  validate:
    uses: ./.github/workflows/call-validate-data-files.yml
